### ISSUE TITLE
GitHub RESTMULE Client crashes when GitHub Server is down

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#198] opened 2019-05-07 09:42 UTC
the project https://github.com/docdoku/docdoku-plm from Jan/01/2018 to Feb/01/2018 , with metric Factoid    "Bug Tracker Usage" ticked in and tell me how it goes ? On my side the task hang on this state:

![2019-05-07_11-40](https://user-images.githubusercontent.com/9987241/57290086-fea68800-70bc-11e9-8a1e-9eb26af9b2a1.png)

With the related log entries:

```
INFO  [ProjectExecutor (w2:docdokuplm:all)] (09:12:49): Updating last executed date.
INFO  [ProjectExecutor (w2:docdokuplm:all)] (09:12:49): Date 20180104 Task Execution ( docdokuplm:all completed in 38223 ms )
INFO  [ProjectExecutor (w2:docdokuplm:all)] (09:12:49): Project docdokuplmTask execution ( docdokuplm:all : Date 20180105 )
INFO  [AnalysisSchedulingService] (09:12:49): Starting new daily execution AnalysisTask 'docdokuplm:all'
INFO  [AnalysisSchedulingService] (09:12:49): Starting new daily execution AnalysisTask 'docdokuplm:all' is done.
INFO  [ProjectExecutor (w2:docdokuplm:all)] (09:12:49): Date: 20180105, project: docdoku-plm
INFO  [ProjectDelta (docdoku-plm,20180105)] (09:12:49): Creating Delta
```

And I also get some seconds later in the logs:

```
2019-05-07T09:13:02.583685019Z 09:13:02.582 ERROR [172] AbstractInterceptor$1 - UNKNOWN ERROR CODE: 502
2019-05-07T09:13:02.584377688Z Exception in thread "pool-255-thread-1" java.lang.UnsupportedOperationException: Do not know how to handle this type of error code: 502
2019-05-07T09:13:02.584402577Z  at org.eclipse.scava.crossflow.restmule.core.interceptor.AbstractInterceptor$1.intercept(AbstractInterceptor.java:173)
2019-05-07T09:13:02.584416052Z  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-07T09:13:02.584418327Z  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-07T09:13:02.584420071Z  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2019-05-07T09:13:02.584421807Z  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
2019-05-07T09:13:02.584423480Z  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2019-05-07T09:13:02.584425271Z  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-05-07T09:13:02.584426973Z  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-05-07T09:13:02.584428645Z  at java.lang.Thread.run(Thread.java:748)
2019-05-07T09:13:04.113049444Z May 07, 2019 9:13:04 AM org.restlet.engine.log.LogFilter afterHandle
```

**Comment by creat89** [comment] 2019-05-07 10:24
I can reproduce the error, however, the day (delta) on which the error happens is random. I've seen the error on the first delta, on the second delta or in the 5th delta. It might be an error due to a GitHub API server downtime. However, when triggered this error, it breaks the platform with an issue that cannot be recovered.

In the case of GitHub the RESTMULE client instead of crashing it should wait some minutes to try again the task. Or at least finish the task better without crashing the platform.

**Comment by mhow2** [comment] 2019-05-10 10:14
Notice that if you wait enough (like 40min), you might see the process to resume:

`INFO  [ProjectDelta (docdoku-plm,20180218)] (09:55:14): Created Delta (2152771 ms)`

So it might not be "crashed" but extremely slowed down by something.

**Comment by mhow2** [comment] 2019-05-10 10:22
flagging @crossminer/york team

**Comment by mhow2** [comment] 2019-05-14 07:25
Reproduced the issue yesterday but this time waiting didn't showed anything more.
I get the same exception as above and the latest entries in the log are:

```
INFO  [ProjectExecutor (w1:spoon:all)] (12:05:51): Date: 20180316, project: spoon
INFO  [ProjectDelta (spoon,20180316)] (12:05:51): Creating Delta

```

**Comment by mhow2** [comment] 2019-05-15 12:45
O/ @patrickneubauer are you able to reproduce this ?
I've been able to analyse the full year 2018 of the project yesterday, all metrics enabled, which is good news. It tooks ~4h.

I noticed that some of the deltas are taking a very long time:

INFO  [ProjectDelta (docdoku-plm,20180205)] (10:23:04): Created Delta (3868331 ms)
INFO  [ProjectDelta (docdoku-plm,20180304)] (11:02:49): Created Delta (1598379 ms)
INFO  [ProjectDelta (docdoku-plm,20180511)] (12:00:53): Created Delta (2192250 ms)
INFO  [ProjectDelta (docdoku-plm,20180910)] (12:36:26): Created Delta (425349 ms)

So indeed in the total analysis time of 4hours, there has been 2,8h just for the four deltas above (!)

Unfortunately I don't have the docker container's logs anymore to correlate with 502's exceptions but I would bet it is related.

**Comment by kb634** [comment] 2019-05-16 11:46
Hi @mhow2 we plan to look at this bug as soon as we wrap up current ongoing developments, very likely within the upcoming week. We will update this thread as soon as we have a solution or need more information, and thank you for the information provided already.

**Comment by mhow2** [comment] 2019-06-04 09:30
@kb634 , @crossminer/york 
See the following screenshot, we still have an issue:

![screen](https://user-images.githubusercontent.com/9987241/58868203-238e1b00-86bc-11e9-8fe1-e14e107d864a.png)

**Comment by creat89** [comment] 2019-06-04 09:33
@mhow2, we might still have the issue as I need to repackage RESTMULE. The current implementation is not Tycho and do not generate any Jenkins, so I need to link it manually.

**Comment by creat89** [comment] 2019-06-04 09:58
@kb634 From which branch of CROSSFLOW/RESTMULE should I create the jar?

**Comment by kb634** [comment] 2019-06-04 11:00
@creat89 Hi Adrian, the patch is in the 'crossflow' branch, I am not closing this issue until you or @mhow2 can verify it fixes the issue. Cheers.

**Comment by creat89** [comment] 2019-06-04 15:44
Commit https://github.com/crossminer/scava/commit/2c187104a8c1091f05999c43de2882a33f6604bb should implement the changes that were done in CROSSFLOW/RESTMULE

**Closed** 2019-07-08 14:38 UTC
