### ISSUE TITLE
Pagination of SCAVA metrics

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#138] opened 2019-03-08 16:01 UTC
I'm using the [docker-compose](https://github.com/crossminer/scava-deployment/blob/dev/docker-compose-build.yml) available in the scava-deployment repo. I'm querying the SCAVA API to collect the metrics of the projects available in the docker-compose

I see that the number of metrics is always the same, but it's not consistent with what listed at http://localhost:5601/project/configure/<project>, see examples below.

It is possible that the results are returned paginated, however I don't see any pagiation param to iterate over the list of metrics. It is also possible that the problem is related to the endpoints I'm using, which are:
- `/metrics/`
- `/factoids/`
- `/projects/`
- `/projects/p/<project-id>/m/<metric-id>`
- `/projects/p/<project-id>/f/<factoid-id>`

I've tried to use the endpoints reported here: https://github.com/crossminer/scava/wiki/REST-API-Documentation#metrics-provider-api, but they don't seem to work.

Any hints @ambpro ?

**emf**
Total metrics collected: 188
306 listed in http://localhost:5601/project/configure/emf

**JDBM**
Total metrics: 188
306 listed in http://localhost:5601/project/configure/JDBM

**Comment by ambpro** [comment] 2019-03-11 09:59
Hi @valeriocos,

> I see that the number of metrics is always the same, but it's not consistent with what listed at http://localhost:5601/project/configure/, see examples below.

First of all, the metric-providers associated to the analysis tasks are coming from `http://localhost:8182/analysis/metricproviders`. On the development environment (locally), the api endpoint returns 306 metrics. ([List of MP](https://api.jsonbin.io/b/5c862c9f2e4731596f1d3312)). 
On the other hand, the same api in the scava-deployment returns 278 metric-providers: http://ci4.castalia.camp:8182/analysis/metricproviders 
As already discussed with @MarcioMateus about that, the problem is related to the metricplatform packaging. @MarcioMateus , could you confirm that ?
For that raison, the dumped provided by the scava-deployment point to 306 metrciproviders, however the metricplatform extension-points couldn't resolve all of them ([filterMetricProvider](https://github.com/crossminer/scava/blob/dev/metric-platform/platform/org.eclipse.scava.platform.osgi/src/org/eclipse/scava/platform/osgi/analysis/ProjectAnalyser.java#L186)).

> I've tried to use the endpoints reported here: https://github.com/crossminer/scava/wiki/REST-API-Documentation#metrics-provider-api, but they don't seem to work.

These APIs endpoints are documentated using the API gateway configuration routing pattern `metricprovidrs`.
In order to call these APIs, you have two ways:
* Through the API gateway: `http://ci4.castalia.camp:8086/administration/metrics`
* Addressing directly the metric-platform: `http://ci4.castalia.camp:8182/metrics`

**Comment by ambpro** [comment] 2019-03-11 10:12
@valeriocos , 
FIY, the `/metric` list only 188 metric-providers that have a visualization associated as mentioned [here](https://github.com/crossminer/scava/issues/62#issuecomment-444532107).

**Comment by valeriocos** [comment] 2019-03-11 13:51
Thank you @ambpro for answering and for the offline discussion. I recap below what I understood (please correct me if you see something inaccurate).

The call http://ci4.castalia.camp:8182/analysis/task?analysisTaskId=emf:analysis returns the execution information of the different metric providers for a given project. The information returned doesn't contain metric values.

The metric data should be retrieved with the [metrics-provider-api](https://github.com/crossminer/scava/wiki/REST-API-Documentation#metrics-provider-api), however the `/metricprovider/raw/metrics` is deprecated while `/metricprovider/metrics` returns only the metrics that have a visualization associated (something that comes from OSSMETER), which should explain the inconsistency between the number of metrics obtained from the SCAVA API and the ones listed with http://ci4.castalia.camp:8182/analysis/metricproviders.

**Comment by davidediruscio** [comment] 2019-03-11 15:30
@valeriocos Yes, your summary is correct. 

In order to avoid further misunderstandings, I would propose to filter the list of metrics that can be applied on a given project (e.g., http://ci4.castalia.camp:5601/project/configure/emf) and show only those that can be actually visualized later in the process. For instance, the list of 306 metrics includes also importers that do not need to be applied at that stage. 

@ambpro does this make sense to you?

**Comment by valeriocos** [comment] 2019-03-11 15:38
I'm trying to use the endpoint `raw/metrics` to overcome the limitation of collecting only metrics with visualizations. The metrics returned don't contain any ID to build the URL to fetch the metrics of a given project (`/projects/p/<project-id>/m/<metric-id>`), so in the current situation it seems that it isn't possible to fetch project metric data using the raw information. Furthermore the raw metric data contains also factoid data (which can be easily filtered out).

I attach below some examples of the raw metrics fetched:
```
{'name': 'Bug Tracker Usage', 
'type': 'org.eclipse.scava.factoid.bugs.channelusage.BugsChannelUsageFactoid', 
'description': 'summaryblah'}
```

```
{'name': 'Number Of Bug Patches Per Day', 
'type': 'org.eclipse.scava.metricprovider.historic.bugs.patches.PatchesHistoricMetricProvider',
'description': 'This class computes the number of bug patches per day.'}
```

```
{'name': 'Commits by day', 
'type': 'org.eclipse.scava.metricprovider.trans.dailycommits.DailyCommitsMetricProvider', 
'description': 'Commits group by the day on which they occurred.'}
```

**Comment by valeriocos** [comment] 2019-03-11 15:39
sorry @davidediruscio I didn't see your last message

**Comment by ambpro** [comment] 2019-03-11 16:44
@davidediruscio @valeriocos 
I think that the current ticket issue treats two different topics:
* The first one is the problem related to the metric-providers loading when the metric platform started (using the extension-points mechnism).
In the context of the scava-deployment, both of `/raw/metrics` and `analysis/metricproviders` list less than what the same two apis return on the local development environment.
* The second problem which dedicated to APIs used to provides metrics analysis data stored on the projects databases which will be used on the web dashboards to create visualizations.
Currently, I suppose that the available OSSMETER APIs doesn't provide yet this service.

So, @davidediruscio @valeriocos  I would like to know if you are ok to reopen two different tickets to separate the two subjects and close this issue #138 and #139 which mix the two topics discussions ?

**Comment by davidediruscio** [comment] 2019-03-11 16:54
Yes please go ahead. thanks

Sent with something mobile

Il lun 11 mar 2019, 17:44 Amin Boudeffa <notifications@github.com> ha
scritto:

**Comment by ambpro** [comment] 2019-03-12 10:00
The scava metric providers loading issue is moved to #143

**Comment by ambpro** [comment] 2019-03-13 08:54
Fetching data metrics discussion from SCAVA API is moved #145

**Closed** 2019-03-13 08:54 UTC
