### ISSUE TITLE
GitHub Reader not retrieving all the issues (Pagination problem)

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#314] opened 2019-07-03 14:08 UTC
With recent build, I tried to analyse https://github.com/eclipse-ee4j/glassfish.git on Jan/2018 with the following metrics enabled:

![2019-07-03_16-06](https://user-images.githubusercontent.com/9987241/60598198-90c0c900-9dac-11e9-927b-ddd7f798cb2c.png)

But I don't get any result for `bugs.bugs`. 
As you can see there are bugs on Jan/3 : https://github.com/eclipse-ee4j/glassfish/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+created%3A2018-01-03

@Danny2097 , @creat89 any idea ?

**Comment by creat89** [comment] 2019-07-03 14:39
I have seen a similar behavior in repositories with large number of issues. But I wasn't sure of the reason until now. The reader seems to not doing the pagination, but I don't know if the error comes from RESTMULE or the GitHub reader.

Currently, I'm seeing a range of only 100 issues, while the number it is much greater. 

@Danny2097, I couldn't find where the pagination should be done. Could you check and if it is an issue with RESTMULE contact to York?

**Comment by Danny2097** [comment] 2019-07-03 18:28
Pagination should be handled by the Github Client generated by RESTMULE. @creat89  I don't know what version of RESTMULE you packaged and included with the Github reader. 
Perhaps this issue has been fixed in a recent version of RESTMULE and it is this that just needs updating since this reader was built over 12 months ago. Maybe it is worth checking that before contacting York.

**Comment by creat89** [comment] 2019-07-03 18:31
The version is the last one of one month or maybe two months ago. As I had to update it for the issue with the reader breaking if Github servers were faulty.

**Comment by creat89** [comment] 2019-07-03 18:34
And no, RESTMULE has not been updated since then.

**Comment by Danny2097** [comment] 2019-07-09 13:25
@patrickneubauer have you experienced any issues regarding pagination when using the Github RESTMULE Client?

**Comment by mhow2** [comment] 2019-08-01 15:54
flagging @kb634

**Comment by mhow2** [comment] 2019-08-01 16:05
@kb634 , to speak about the pagination issue, I suppose that the URL used with cURL is inspired from https://developer.github.com/v3/#pagination
For example, https://api.github.com/repos/ow2-proactive/scheduling/issues?per_page=200
Notice that in this example, the number of entries is capped to 100 even if we ask more. It could be a lead to address the issue.

**Comment by mhow2** [comment] 2019-08-06 09:00
@kolovos please don't forget us. We need this solved asap.

**Comment by kb634** [comment] 2019-08-06 11:23
@mhow2 we have replicated the issue and are looking into ways to tackle it, we will let you know when it is solved or if we can use any more input/insight into the matter, cheers.

**Comment by kb634** [comment] 2019-08-06 17:29
@Danny2097 when you can, please incorporate the latest changes into the reader and let us know whether the issue is solved. Please note that for your example query, there are 229 pages (22801-22900 issues) available so it may take a while to run.

**Comment by creat89** [comment] 2019-08-06 18:01
I'll do the changes tomorrow morning

Sent from my phone

________________________________

**Comment by creat89** [comment] 2019-08-07 12:32
Hello @mhow2,

I have just pushed the modification done by @kb634. It should be available like in one hour after Jenkins has created the builds. I'll test it locally later and see if the issue is solved.

**Comment by creat89** [comment] 2019-08-07 13:12
@mhow2, the update will take longer

**Comment by creat89** [comment] 2019-08-07 13:28
@mhow2, in my last commit 4ac155144c7f63167c5bd10cc6c2d046a01a1368 I have fixed this issue. With the tests that I've been doing, now I can see the bugs of the 3rd January 2018. I will close the issue, but if it occurs again, let us know. The fix should be available in Jenkins around 5pm time of Paris on the 7th August 2019.

Thanks @kb634 for the fix!

**Closed by creat89** 2019-08-07 13:28 UTC
Labels: bug
