### ISSUE TITLE
dashboards : gaps and labels

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#356] opened 2019-09-13 10:27 UTC
# gaps #
For ex, on my kibiter instance I have "no data" for "Old and new dependencies versions".
In order to demonstrate the dashboards, we need either to fill all the gaps or provide a good explanation why some viz are empty.

# labels # 

About labels, we need better legend for those kind of viz:
![image](https://user-images.githubusercontent.com/9987241/64856098-89763100-d621-11e9-82b4-6dbf76656412.png)
![image](https://user-images.githubusercontent.com/9987241/64856121-95fa8980-d621-11e9-82cb-a46e71dd43be.png)
![image](https://user-images.githubusercontent.com/9987241/64856141-9dba2e00-d621-11e9-8505-061e0d7f624c.png)
(etc)

tag @valeriocos

**Comment by valeriocos** [comment] 2019-09-13 10:46
wrt to gaps, I have seen the same problem. @blueoly do you have some idea about it?

wrt labels, I'll check how to improve it

thanks

**Comment by blueoly** [comment] 2019-09-16 16:16
Hi @valeriocos !

About the gaps that have to do with AUEB metrics, the reason behind them is the cause of the #309 . I am working at it. When it is solved, there will no be any gaps

**Comment by blueoly** [comment] 2019-09-16 16:19
There is also the case that there are no new versions, for example, in some projects. Even if I solve #309 , I think that there will be gaps.

**Comment by blueoly** [comment] 2019-09-23 04:39
@valeriocos I found the two following issues about the devops dashboards, that should be fixed.

In scava-devops-smells the Puppet Smells viz does not showing the puppet smells historic metrics but the Docker Smells metrics.
In scava-devops-deps and scava-deps, the new dependencies viz do not show the data, despite that the data are calculated and stored in mongodb. So, they stay always empty.

Especially the second issue is very strange, as the last time I have checked during summer, there was no problem at all.

Also, please tell me if you want any help with the viz labels.

**Comment by valeriocos** [comment] 2019-09-23 06:00
Thank you @blueoly for reporting these problems.
I'll check the puppet smells in my instance today and let you know.

WRT the scava-devops-deps and scava-deps, did you check if the data is visible through the API endpoints? Scava2es and Perceval don't query the mongoDB.

We can sync on Slack today, if it's OK for you.

**Comment by valeriocos** [comment] 2019-09-27 14:17
labels fixed with https://github.com/crossminer/scava/pull/378

**Comment by valeriocos** [comment] 2019-09-27 15:50
@mhow2 let's close this issue, feel free to reopen it if needed, thanks

**Closed by valeriocos** 2019-09-27 15:50 UTC
